# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-12 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=50)),
                ('opreate_id', models.CharField(default='platform', max_length=50)),
                ('copyfor', models.CharField(max_length=50, null=True)),
                ('question', models.CharField(choices=[('1', '问询'), ('2', '任务'), ('3', '问题'), ('4', '事件'), ('5', '其他')], max_length=20)),
                ('service_list', models.CharField(max_length=50)),
                ('order_status', models.IntegerField(choices=[('0', '未受理'), ('1', '处理中'), ('2', '已解决'), ('3', '已关闭'), ('4', '延期'), ('5', '超时'), ('9', '已关闭')], default=0, max_length=20)),
                ('sign', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=256, null=True)),
                ('priority', models.CharField(choices=[('P0', '紧急'), ('P1', '高'), ('P2', '中'), ('P3', '低')], max_length=10)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderOperate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('operate_id', models.IntegerField()),
                ('from_priority', models.CharField(max_length=30)),
                ('to_priority', models.CharField(max_length=30)),
                ('from_status', models.IntegerField()),
                ('to_status', models.IntegerField()),
                ('from_copyfor', models.CharField(max_length=30)),
                ('to_copyfor', models.CharField(max_length=30)),
                ('replay', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'order_operate',
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('service_name', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'service_list',
            },
        ),
    ]
