# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(choices=[('0', '未受理'), ('1', '处理中'), ('2', '已解决'), ('3', '已关闭'), ('4', '延期'), ('5', '超时'), ('9', '已关闭')], default=0),
        ),
    ]
