# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderinfo_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='remarks',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='sign',
            field=models.CharField(max_length=30),
        ),
    ]
