# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190819_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoperate',
            name='from_opreate_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderoperate',
            name='to_opreate_id',
            field=models.IntegerField(default=1),
        ),
    ]
