# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190819_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='opreate_id',
            field=models.IntegerField(),
        ),
    ]
