# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderinfo_opreate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='opreate_name',
            field=models.CharField(max_length=50),
        ),
    ]
