# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190819_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='complete_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
