# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-21 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190820_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 9, 18, 41, 917856)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 9, 18, 41, 917856)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 9, 18, 41, 917856)),
        ),
    ]
