# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190819_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderoperate',
            name='operate_id',
        ),
    ]
