# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderoperate_operate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoperate',
            name='replay',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
