# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-21 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190821_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 3, 24, 164235)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 3, 24, 164235)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 3, 24, 164235)),
        ),
    ]
