# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-20 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190820_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderoperate',
            old_name='order_name',
            new_name='opreate_name',
        ),
    ]
