# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-21 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190821_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 13, 30, 41211)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 13, 30, 41211)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 13, 30, 41211)),
        ),
    ]
