# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-12 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('customer_group', models.CharField(choices=[('1', 'xxx'), ('2', 'xxx'), ('3', 'xxx')], max_length=30)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('support_group', models.CharField(choices=[('1', '售后维护'), ('2', 'it组1')], max_length=30)),
                ('pid', models.IntegerField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'support',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(default='123456', max_length=30)),
                ('company_name', models.CharField(default='克亚科技公司', max_length=30)),
                ('role', models.ImageField(choices=[('0', 'admin'), ('1', '客服经理'), ('2', '客服')], default=2, upload_to='')),
                ('pid', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
