# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-22 15:04
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('urole', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('ugid', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'abstract': False,
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientGroupTable',
            fields=[
                ('cgid', models.AutoField(primary_key=True, serialize=False)),
                ('cgname', models.CharField(blank=True, max_length=32, null=True)),
                ('cgnotes', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('ugid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_group_table',
            },
        ),
        migrations.CreateModel(
            name='ClientTable',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=32, null=True)),
                ('cnickname', models.CharField(blank=True, max_length=32, null=True)),
                ('ccontactemail', models.CharField(blank=True, db_column='ccontactEmail', max_length=128, null=True)),
                ('cvalid', models.IntegerField(blank=True, null=True)),
                ('cmobilephone', models.IntegerField(blank=True, db_column='cmobilePhone', null=True)),
                ('cnotes', models.CharField(blank=True, max_length=255, null=True)),
                ('ccreatedat', models.DateTimeField(blank=True, db_column='ccreatedAt', null=True)),
                ('cupdatedat', models.DateTimeField(blank=True, db_column='cupdatedAt', null=True)),
                ('cgid', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('customercustomfields', models.CharField(blank=True, db_column='customerCustomFields', max_length=255, null=True)),
            ],
            options={
                'db_table': 'client_table',
            },
        ),
        migrations.CreateModel(
            name='TypesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'types_table',
            },
        ),
        migrations.CreateModel(
            name='UserGroupTable',
            fields=[
                ('ugid', models.AutoField(primary_key=True, serialize=False)),
                ('ugname', models.CharField(blank=True, max_length=32, null=True)),
                ('ugdescription', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'user_group_table',
            },
        ),
    ]
