# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='urole',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
