# -*- coding: utf-8 -*-
<<<<<<< HEAD:tasking/users/migrations/0002_auto_20190819_1548.py
# Generated by Django 1.11.16 on 2019-08-19 15:48
=======
# Generated by Django 1.11.16 on 2019-08-18 21:36
>>>>>>> Ei-mago:tasking/orders/migrations/0003_orderinfo_finish_time.py
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD:tasking/users/migrations/0002_auto_20190819_1548.py
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
=======
        ('orders', '0002_auto_20190812_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='finish_time',
            field=models.DateTimeField(null=True),
>>>>>>> Ei-mago:tasking/orders/migrations/0003_orderinfo_finish_time.py
        ),
    ]
