# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190819_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(default=0),
        ),
    ]
