# -*- coding: utf-8 -*-
<<<<<<< HEAD:tasking/orders/migrations/0003_orderinfo_finish_time.py
# Generated by Django 1.11.16 on 2019-08-18 21:36
=======
# Generated by Django 1.11.16 on 2019-08-19 15:49
>>>>>>> 95a6ce88532470cac2b9be43afcaab4a4b89ea55:tasking/users/migrations/0003_auto_20190819_1549.py
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD:tasking/orders/migrations/0003_orderinfo_finish_time.py
        ('orders', '0002_auto_20190812_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='finish_time',
            field=models.DateTimeField(null=True),
=======
        ('users', '0002_auto_20190819_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(default=0),
>>>>>>> 95a6ce88532470cac2b9be43afcaab4a4b89ea55:tasking/users/migrations/0003_auto_20190819_1549.py
        ),
    ]
