# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190822_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='cgid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
