# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190823_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='cmobilephone',
            field=models.CharField(blank=True, db_column='cmobilePhone', max_length=30, null=True),
        ),
    ]
