# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190819_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
