# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190819_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='cmobilephone',
            field=models.CharField(blank=True, db_column='cmobilePhone', max_length=11, null=True),
        ),
    ]
