# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190819_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='cgid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
